PREFIX owl: http://www.w3.org/2002/07/owl
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema
PREFIX parking: http://example.com/parking/

#Resultado de la query: Madrid
SELECT DISTINCT ?BARRIO
    WHERE{
        ?BARRIO rdf:type http://example.com/parking/barrio.
    }

#Resultado de la query: La Moraleja
SELECT DISTINCT ?NOMBRE_CALLE
    WHERE{
        ?NOMBRE_CALLE rdf:type http://example.com/parking/nombre_calle.
    }